### ISSUE TITLE
dependency is broken

### ISSUE THREAD

**Issue by VisheshJaiswal** [Pranav433/screen_recorder#1]
After installing the package, I get the below error when I try to run the code.
```
Traceback (most recent call last):
  File ".\timer.py", line 2, in <module>
    from screen_recorder import Recorder
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\screen_recorder\__init__.py", line 1, in <module>
    from . import cli
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\screen_recorder\cli.py", line 1, in <module>
    import enquiries
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\enquiries\__init__.py", line 2, in <module>
    from enquiries.yesno import confirm
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\enquiries\yesno.py", line 3, in <module>
    from curtsies import Input, FSArray , CursorAwareWindow, fsarray
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\curtsies\__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\curtsies\window.py", line 29, in <module>
    import blessings
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by Pranav433** [comment]
I think you should do "pip install fcntl'
might help

**Comment by Pranav433** [comment]
And make sure u have the ffmpeg binary https://youtu.be/r1AtmY-RMyQ follow this video if you don't have ffmpeg installed and make sure you add ffmpeg to PATH

**Comment by Pranav433** [comment]
i think the pip install screen_recorder is installing some other module, i think you should
install this module like this
`
git clone https://github.com/Pranav433/screen_recorder
cd screen_recorder
pip install .
`
